# Generated by Django 6.0.4 on 2026-05-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0004_enrollmentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentrequest',
            name='reason',
            field=models.TextField(default='No reason provided'),
            preserve_default=False,
        ),
    ]
