# Generated by Django 6.0.4 on 2026-05-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0005_enrollmentrequest_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentrequest',
            name='reason',
            field=models.TextField(blank=True),
        ),
    ]
