# Generated by Django 6.0.3 on 2026-05-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0007_waitlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentrequest',
            name='issue',
            field=models.CharField(choices=[('full', 'Course Full'), ('prerequisites', 'Missing Prerequisites')], default='full', max_length=20),
        ),
    ]
