# Generated by Django 6.0.4 on 2026-05-10 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
