# Generated by Django 6.0.4 on 2026-04-27 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_instructor_course_seating_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='seating_limit',
            field=models.IntegerField(default=1),
        ),
    ]
