# Generated by Django 6.0.4 on 2026-04-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_prerequisites'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='time',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
